# Generated by Django 4.2 on 2024-08-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizentry',
            options={'verbose_name_plural': 'Quizz Entries'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='response',
            new_name='quiz_entry',
        ),
    ]
