# Generated by Django 4.2 on 2024-08-28 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_quiz_options_alter_quizentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('item__order',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, help_text='Passing Score (%)', validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
