# Generated by Django 4.2 on 2024-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_answer_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
