# Generated by Django 4.2 on 2024-08-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_quiz_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('quiz_entry', 'item')},
        ),
    ]
